services:
  angular:
    container_name: angular
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "4200:4200"
    command: >
      sh -c "npm install &&
            npm run start"
    volumes:
      - ./fe-ema:/usr/src/app
    env_file:
      - ./.env
